#!/bin/sh

set -e

echo "======================================"
echo "      Linux BBR v3 一键启用脚本"
echo "======================================"
echo

########################################
# 系统信息
########################################

if [ -f /etc/os-release ]; then
    . /etc/os-release
    echo "检测到系统: ${PRETTY_NAME}"
else
    echo "无法识别系统"
    exit 1
fi

echo
echo "当前内核:"
KERNEL_VERSION=$(uname -r)
uname -r
echo

########################################
# 内核版本检查 (BBR v3 需要 Linux 6.1+)
########################################

KERNEL_MAJOR=$(echo $KERNEL_VERSION | cut -d. -f1)
KERNEL_MINOR=$(echo $KERNEL_VERSION | cut -d. -f2)

if [ "$KERNEL_MAJOR" -lt 6 ] || ([ "$KERNEL_MAJOR" -eq 6 ] && [ "$KERNEL_MINOR" -lt 1 ]); then
    echo "错误: BBR v3 需要 Linux 6.1 或更高版本"
    echo "当前内核版本: $KERNEL_VERSION"
    echo "请升级内核后重试"
    exit 1
fi

echo "✓ 内核版本满足要求 (>= 6.1)"
echo

########################################
# 依赖检查
########################################

echo "检查依赖..."

# 检查 sysctl
if ! command -v sysctl >/dev/null 2>&1; then
    echo "错误: 未找到 sysctl"
    echo "请先安装 procps/procps-ng"
    exit 1
fi
echo "✓ sysctl 已安装"

# 检查 modprobe
if ! command -v modprobe >/dev/null 2>&1; then
    echo "错误: 未找到 modprobe"
    echo "请先安装 kmod"
    exit 1
fi
echo "✓ modprobe 已安装"

# 检查 lsmod
if ! command -v lsmod >/dev/null 2>&1; then
    echo "错误: 未找到 lsmod"
    exit 1
fi
echo "✓ lsmod 已安装"

echo

########################################
# BBR v3 支持检查
########################################

echo "检查 BBR v3 支持..."

# 检查可用的拥塞控制算法
AVAILABLE="$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)"

if [ -z "$AVAILABLE" ]; then
    echo "错误: 无法读取 tcp_available_congestion_control"
    exit 1
fi

echo "可用拥塞控制算法:"
echo "$AVAILABLE"
echo

# 检查 BBR 支持
if ! echo "$AVAILABLE" | grep -qw bbr; then
    echo "错误: 当前内核不支持 BBR"
    echo "请确保:"
    echo "  1. 内核版本 >= 6.1"
    echo "  2. 内核编译时启用了 CONFIG_TCP_CONG_BBR"
    echo "  3. 如果使用自定义内核,请参考:"
    echo "     https://github.com/google/bbr/blob/v3/README.md"
    exit 1
fi

echo "✓ 检测到 BBR 支持"
echo

########################################
# 检查 BBR 版本
########################################

echo "检查 BBR 版本..."

# 尝试获取 BBR 版本信息
if [ -f /sys/module/tcp_bbr/version ]; then
    BBR_VERSION=$(cat /sys/module/tcp_bbr/version)
    echo "当前 BBR 版本: $BBR_VERSION"
else
    echo "! 无法读取 BBR 版本信息"
fi

echo

########################################
# fq qdisc 检测
########################################

echo "检查 fq qdisc 支持..."

USE_FQ=0

if [ -f /proc/sys/net/core/default_qdisc ]; then
    USE_FQ=1
    CURRENT_QDISC=$(cat /proc/sys/net/core/default_qdisc)
    echo "✓ 检测到 fq qdisc 支持"
    echo "  当前 qdisc: $CURRENT_QDISC"
else
    echo "! 未检测到 default_qdisc,将仅启用 BBR"
fi

echo

########################################
# ECN 支持检查
########################################

echo "检查 ECN 支持..."

if sysctl net.ipv4.tcp_ecn >/dev/null 2>&1; then
    ECN_STATUS=$(sysctl -n net.ipv4.tcp_ecn)
    echo "✓ 系统支持 ECN"
    echo "  当前 ECN 状态: $ECN_STATUS"
else
    echo "! 系统不支持 ECN"
fi

echo

########################################
# 写入配置
########################################

echo "写入 BBR v3 配置..."

mkdir -p /etc/sysctl.d

CONF="/etc/sysctl.d/99-bbr-v3.conf"

cat > "$CONF" <<'EOF'
# BBR v3 Congestion Control Configuration
# Generated by BBR v3 Installation Script

# 启用 BBR v3 拥塞控制
net.ipv4.tcp_congestion_control=bbr

# 使用 fq qdisc (推荐)
net.core.default_qdisc=fq

# TCP 缓冲区优化
net.core.rmem_max=134217728
net.core.wmem_max=134217728
net.ipv4.tcp_rmem=4096 87380 134217728
net.ipv4.tcp_wmem=4096 65536 134217728

# TCP 性能调优
net.ipv4.tcp_window_scaling=1
net.ipv4.tcp_timestamps=1
net.ipv4.tcp_sack=1
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_moderate_rcvbuf=1

# 网络栈优化
net.core.netdev_max_backlog=5000
net.ipv4.tcp_slow_start_after_idle=0

# ECN 支持 (可选,用于 BBR v3 ECN 功能)
# net.ipv4.tcp_ecn=1

# TCP 快速打开 (可选)
# net.ipv4.tcp_fastopen=3
EOF

echo "配置已写入: $CONF"
echo

########################################
# 加载 BBR 模块
########################################

echo "加载 BBR 模块..."

if ! modprobe tcp_bbr 2>/dev/null; then
    echo "! 无法加载 tcp_bbr 模块"
    echo "  这可能是因为:"
    echo "  1. 内核未编译 BBR 支持"
    echo "  2. 在容器环境中运行"
    echo "  继续应用配置..."
else
    echo "✓ BBR 模块已加载"
fi

# 使模块加载持久化
if ! grep -q "tcp_bbr" /etc/modules-load.d/modules.conf 2>/dev/null; then
    echo "tcp_bbr" >> /etc/modules-load.d/modules.conf
    echo "✓ 已添加到模块自动加载列表"
fi

echo

########################################
# 应用配置
########################################

echo "应用 sysctl 配置..."

if sysctl -p "$CONF" >/dev/null 2>&1; then
    echo "✓ 配置已应用"
else
    echo "! 应用配置时出现警告,继续验证..."
fi

# 重新加载所有 sysctl 配置
sysctl --system >/dev/null 2>&1 || true

echo

########################################
# 验证结果
########################################

echo "验证 BBR v3 配置..."
echo "======================================"

# 检查拥塞控制算法
CURRENT_CC=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || true)

if [ "$CURRENT_CC" = "bbr" ]; then
    echo "✓ BBR v3 已成功启用"
    echo "  当前拥塞控制: $CURRENT_CC"
else
    echo "! BBR v3 配置已写入,但当前未生效"
    echo "  当前拥塞控制: ${CURRENT_CC:-unknown}"
    echo
    echo "可能原因:"
    echo "  1. 宿主机限制 (容器环境)"
    echo "  2. 容器未开放相关 sysctl"
    echo "  3. 需要重启系统/容器"
    echo "  4. 内核未编译 BBR 支持"
fi

echo

# 检查 qdisc
if [ -f /proc/sys/net/core/default_qdisc ]; then
    CURRENT_QDISC=$(sysctl -n net.core.default_qdisc 2>/dev/null || true)
    if [ "$CURRENT_QDISC" = "fq" ]; then
        echo "✓ fq qdisc 已启用"
    else
        echo "! 当前 qdisc: ${CURRENT_QDISC:-unknown}"
    fi
    echo
fi

# 检查 ECN
ECN_STATUS=$(sysctl -n net.ipv4.tcp_ecn 2>/dev/null || true)
if [ -n "$ECN_STATUS" ]; then
    echo "ECN 状态: $ECN_STATUS"
    if [ "$ECN_STATUS" = "1" ]; then
        echo "✓ ECN 已启用 (BBR v3 可使用 ECN 功能)"
    fi
    echo
fi

########################################
# 详细状态信息
########################################

echo "详细配置状态:"
echo "======================================"

echo
echo "拥塞控制相关:"
sysctl net.ipv4.tcp_congestion_control 2>/dev/null || echo "! 无法读取"
sysctl net.ipv4.tcp_available_congestion_control 2>/dev/null || echo "! 无法读取"

echo
echo "队列规则相关:"
if [ -f /proc/sys/net/core/default_qdisc ]; then
    sysctl net.core.default_qdisc 2>/dev/null || echo "! 无法读取"
fi

echo
echo "TCP 缓冲区:"
sysctl net.core.rmem_max 2>/dev/null || echo "! 无法读取"
sysctl net.core.wmem_max 2>/dev/null || echo "! 无法读取"

echo
echo "BBR 模块状态:"
if lsmod | grep -q tcp_bbr; then
    echo "✓ BBR 模块已加载"
    lsmod | grep tcp_bbr
else
    echo "! BBR 模块未加载"
fi

echo

########################################
# 完成信息
########################################

echo "======================================"
echo "BBR v3 配置完成!"
echo "======================================"
echo

if [ "$CURRENT_CC" = "bbr" ]; then
    echo "✓ BBR v3 已成功启用"
    echo
    echo "建议:"
    echo "  1. 运行性能测试验证效果"
    echo "  2. 监控网络性能指标"
    echo "  3. 根据需要调整 TCP 缓冲区大小"
else
    echo "⚠ BBR v3 配置已完成,但需要重启系统生效"
    echo
    echo "后续步骤:"
    echo "  1. 重启系统: reboot"
    echo "  2. 重启后验证: sysctl net.ipv4.tcp_congestion_control"
    echo
    echo "如果重启后仍未生效,请检查:"
    echo "  1. 内核版本是否 >= 6.1"
    echo "  2. 内核是否编译了 BBR 支持"
    echo "  3. 是否在容器环境中运行"
fi

echo
echo "配置文件位置: $CONF"
echo "日志位置: /var/log/syslog (或 journalctl -xe)"
echo

########################################
# 可选: 性能测试建议
########################################

echo "性能测试建议:"
echo "======================================"
echo
echo "1. 安装测试工具:"
echo "   apt-get install -y iperf3 netperf"
echo
echo "2. 测试带宽:"
echo "   iperf3 -c <server_ip> -t 60"
echo
echo "3. 监控连接状态:"
echo "   ss -i | grep bbr"
echo
echo "4. 查看详细统计:"
echo "   cat /proc/net/sockstat"
echo

exit 0
