#!/bin/bash

set -e

echo "======================================"
echo "      Linux BBR 一键启用脚本"
echo "======================================"
echo


if [ -f /etc/os-release ]; then
. /etc/os-release
OS="$ID"
else
echo "✘ 无法识别系统"
exit 1
fi

echo "检测到系统: $PRETTY_NAME"
echo


CONTAINER=0

if [ -f /.dockerenv ]; then
CONTAINER=1
fi

if grep -qaE 'docker|lxc|containerd|kubepods' /proc/1/cgroup 2>/dev/null; then
CONTAINER=1
fi

if [ "$CONTAINER" -eq 1 ]; then
echo "⚠ 检测到容器环境"
echo "  BBR 是否可用取决于宿主机内核"
echo
fi


install_sysctl_if_needed() {

```
if command -v sysctl >/dev/null 2>&1; then
    echo "✔ sysctl 已存在"
    return
fi

echo "未检测到 sysctl，尝试安装..."

case "$OS" in

    debian|ubuntu)
        apt-get update -y
        apt-get install -y procps
        ;;

    centos|rhel)
        yum install -y procps-ng
        ;;

    rocky|almalinux|fedora)
        dnf install -y procps-ng
        ;;

    alpine)
        apk add --no-cache procps-ng
        ;;

    *)
        echo "✘ 不支持自动安装依赖"
        exit 1
        ;;
esac

command -v sysctl >/dev/null 2>&1 || {
    echo "✘ sysctl 安装失败"
    exit 1
}
```

}

install_sysctl_if_needed


echo
echo "当前内核:"
uname -r
echo


AVAILABLE=$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)

if [ -z "$AVAILABLE" ]; then
echo "✘ 无法读取 tcp_available_congestion_control"
exit 1
fi

echo "可用拥塞控制:"
echo "$AVAILABLE"
echo

if ! echo "$AVAILABLE" | grep -qw bbr; then

```
echo "✘ 当前内核不支持 BBR"

KERNEL_MAJOR=$(uname -r | cut -d. -f1)
KERNEL_MINOR=$(uname -r | cut -d. -f2)

if [ "$KERNEL_MAJOR" -lt 4 ] || \
   { [ "$KERNEL_MAJOR" -eq 4 ] && [ "$KERNEL_MINOR" -lt 9 ]; }; then

    echo
    echo "原因: 内核版本低于 4.9"
else
    echo
    echo "原因: 当前内核未编译 BBR"
    echo "常见于 OpenVZ/LXC 等共享内核环境"
fi

exit 1
```

fi

echo "✔ 内核支持 BBR"


ENABLE_FQ=0

if [ -f /proc/sys/net/core/default_qdisc ]; then
ENABLE_FQ=1
echo "✔ 检测到 fq 队列支持"
else
echo "⚠ 未检测到 default_qdisc，跳过 fq 配置"
fi


echo
echo "写入配置..."

mkdir -p /etc/sysctl.d

CONF_FILE="/etc/sysctl.d/99-bbr.conf"

cat > "$CONF_FILE" <<EOF

# Generated by BBR Script

net.ipv4.tcp_congestion_control=bbr
EOF

if [ "$ENABLE_FQ" -eq 1 ]; then
cat >> "$CONF_FILE" <<EOF
net.core.default_qdisc=fq
EOF
fi


echo "应用配置..."

if sysctl --system >/dev/null 2>&1; then
:
else
sysctl -p "$CONF_FILE" >/dev/null 2>&1 || true
fi


echo
echo "验证结果:"
echo "--------------------------------------"

CURRENT=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")

if [ "$CURRENT" = "bbr" ]; then
echo "✔ BBR 启用成功"
else
echo "✘ BBR 未生效"
echo "当前值: $CURRENT"
exit 1
fi

echo
echo "当前状态:"

sysctl net.ipv4.tcp_congestion_control 2>/dev/null || true

if [ -f /proc/sys/net/core/default_qdisc ]; then
sysctl net.core.default_qdisc 2>/dev/null || true
fi

echo
echo "诊断信息:"

echo -n "Kernel: "
uname -r

echo -n "Virtualization: "
if command -v systemd-detect-virt >/dev/null 2>&1; then
systemd-detect-virt || echo "none"
else
echo "unknown"
fi

echo
echo "======================================"
echo "完成"
echo "======================================"
