#!/bin/sh

set -e

echo "======================================"
echo "      Linux BBR 一键启用脚本"
echo "======================================"
echo

########################################

# 系统信息

########################################

if [ -f /etc/os-release ]; then
. /etc/os-release
echo "检测到系统: ${PRETTY_NAME}"
else
echo "无法识别系统"
fi

echo
echo "当前内核:"
uname -r
echo

########################################

# sysctl检查

########################################

if ! command -v sysctl >/dev/null 2>&1; then
echo "错误: 未找到 sysctl"
echo "请先安装 procps/procps-ng"
exit 1
fi

########################################

# 检查BBR支持

########################################

AVAILABLE="$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)"

if [ -z "$AVAILABLE" ]; then
echo "无法读取 tcp_available_congestion_control"
exit 1
fi

echo "可用拥塞控制算法:"
echo "$AVAILABLE"
echo

if ! echo "$AVAILABLE" | grep -qw bbr; then
echo "当前内核不支持 BBR"
exit 1
fi

echo "✓ 检测到 BBR 支持"

########################################

# fq检测（可选）

########################################

USE_FQ=0

if [ -f /proc/sys/net/core/default_qdisc ]; then
USE_FQ=1
echo "✓ 检测到 fq 支持"
else
echo "! 未检测到 default_qdisc，仅启用 BBR"
fi

echo

########################################

# 写入配置

########################################

mkdir -p /etc/sysctl.d

CONF="/etc/sysctl.d/99-bbr.conf"

cat > "$CONF" <<EOF

# Generated by BBR Script

net.ipv4.tcp_congestion_control=bbr
EOF

if [ "$USE_FQ" = "1" ]; then
cat >> "$CONF" <<EOF
net.core.default_qdisc=fq
EOF
fi

echo "配置已写入:"
echo "$CONF"
echo

########################################

# 应用配置

########################################

echo "应用配置..."

sysctl --system >/dev/null 2>&1 || true

########################################

# 验证结果

########################################

CURRENT="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || true)"

echo
echo "验证结果:"
echo "--------------------------------------"

if [ "$CURRENT" = "bbr" ]; then
echo "✓ BBR 已成功启用"
else
echo "! BBR 配置已写入，但当前未生效"
echo
echo "当前算法: ${CURRENT:-unknown}"
echo
echo "可能原因:"
echo "  1. 宿主机限制"
echo "  2. 容器未开放相关 sysctl"
echo "  3. 需要重启系统/容器"
fi

echo
echo "当前状态:"

sysctl net.ipv4.tcp_congestion_control 2>/dev/null || true

if [ -f /proc/sys/net/core/default_qdisc ]; then
sysctl net.core.default_qdisc 2>/dev/null || true
fi

echo
echo "======================================"
echo "完成"
echo "======================================"
