#!/bin/sh

set -e

echo "======================================"
echo "      Linux BBR 一键启用脚本"
echo "======================================"
echo

########################################

# 系统识别

########################################

if [ -f /etc/os-release ]; then
. /etc/os-release
OS="$ID"
echo "检测到系统: $PRETTY_NAME"
else
echo "无法识别系统"
exit 1
fi

echo

########################################

# 容器检测

########################################

IS_CONTAINER=0

if [ -f /.dockerenv ]; then
IS_CONTAINER=1
fi

if grep -qaE 'docker|lxc|containerd|kubepods' /proc/1/cgroup 2>/dev/null; then
IS_CONTAINER=1
fi

if [ "$IS_CONTAINER" = "1" ]; then
echo "检测到容器环境（Docker/LXC/LXD）"
echo "BBR 是否可启用取决于宿主机内核"
echo
fi

########################################

# sysctl检查

########################################

install_procps() {

```
case "$OS" in

    debian|ubuntu)
        apt-get update -qq
        apt-get install -y procps
        ;;

    centos|rhel)
        yum install -y procps-ng
        ;;

    rocky|almalinux|fedora)
        dnf install -y procps-ng
        ;;

    alpine)
        apk add --no-cache procps-ng
        ;;

    *)
        echo "未知系统，无法安装 procps"
        exit 1
        ;;
esac
```

}

if ! command -v sysctl >/dev/null 2>&1; then
echo "sysctl 不存在，尝试安装..."
install_procps
fi

if ! command -v sysctl >/dev/null 2>&1; then
echo "sysctl 安装失败"
exit 1
fi

########################################

# 内核信息

########################################

echo "当前内核:"
uname -r
echo

########################################

# 检查BBR支持

########################################

AVAILABLE=$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)

if [ -z "$AVAILABLE" ]; then
echo "无法读取 tcp_available_congestion_control"
echo "当前环境可能不允许修改 TCP 参数"
exit 1
fi

echo "可用拥塞控制算法:"
echo "$AVAILABLE"
echo

if ! echo "$AVAILABLE" | grep -qw bbr; then
echo "当前内核不支持 BBR"
echo

```
MAJOR=$(uname -r | cut -d. -f1)
MINOR=$(uname -r | cut -d. -f2)

if [ "$MAJOR" -lt 4 ] || \
   { [ "$MAJOR" -eq 4 ] && [ "$MINOR" -lt 9 ]; }; then
    echo "原因: 内核版本低于 4.9"
else
    echo "原因: 宿主机未编译 BBR 或容器未开放"
fi

exit 1
```

fi

echo "内核支持 BBR"
echo

########################################

# 检查 fq

########################################

USE_FQ=0

if [ -f /proc/sys/net/core/default_qdisc ]; then
USE_FQ=1
fi

########################################

# 测试是否有写权限

########################################

CURRENT=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "")

if sysctl -w net.ipv4.tcp_congestion_control=bbr >/dev/null 2>&1; then
echo "检测到可修改 tcp_congestion_control"
else
echo "警告: 当前环境不允许修改 tcp_congestion_control"
echo "如果是 LXD/LXC，请在宿主机启用 BBR"
exit 1
fi

########################################

# 写配置

########################################

mkdir -p /etc/sysctl.d

CONF=/etc/sysctl.d/99-bbr.conf

echo "写入配置: $CONF"

cat > "$CONF" <<EOF

# Generated by BBR Script

net.ipv4.tcp_congestion_control=bbr
EOF

if [ "$USE_FQ" = "1" ]; then
cat >> "$CONF" <<EOF
net.core.default_qdisc=fq
EOF
fi

########################################

# 应用配置

########################################

if command -v sysctl >/dev/null 2>&1; then
sysctl --system >/dev/null 2>&1 || true
fi

########################################

# 验证

########################################

echo
echo "验证结果:"
echo "--------------------------------------"

CONG=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")

if [ "$CONG" = "bbr" ]; then
echo "BBR 启用成功"
else
echo "BBR 未生效"
echo "当前算法: $CONG"
exit 1
fi

echo
sysctl net.ipv4.tcp_congestion_control 2>/dev/null || true

if [ -f /proc/sys/net/core/default_qdisc ]; then
sysctl net.core.default_qdisc 2>/dev/null || true
fi

echo
echo "======================================"
echo "完成"
echo "======================================"
